feat: PDM support
Mr-Sunglasses/bitssh pull request #10
Opened 2024-01-12 10:00 UTC by SAMAD101

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #5

## Type of change
Just added PDM support
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-04-06 21:08 UTC, Mr-Sunglasses reviewed
Also to ensure that all the files is typed we need to add `py.typed` empty file to `src/bitssh/`

2024-04-06 21:08 UTC, Mr-Sunglasses commented on src/bitssh/prompt.py
>          HOST = ConfigPathUtility.get_config_file_host_data()
This variable should be typed

2024-04-06 21:08 UTC, Mr-Sunglasses commented on src/bitssh/prompt.py
>          questions = [
This should also be typed

2024-04-06 22:05 UTC, SAMAD101 commented on pyproject.toml
> +build-backend = "pdm.backend"
understood

2024-04-06 22:05 UTC, SAMAD101 commented on pyproject.toml
>  dependencies = [
sure

2024-06-27 18:29 UTC, Mr-Sunglasses requested changes
Any updates?

2024-07-02 06:22 UTC, SAMAD101 commented
yeah, did a little refactor and added `py.typed` file in `src/bitssh/`

2024-07-02 06:30 UTC, Mr-Sunglasses commented
@SAMAD101 Can you please resolve the conflicts.

2024-07-02 06:35 UTC, SAMAD101 commented
> @SAMAD101 Can you please resolve the conflicts.

sure
seems like my branch was too old, that's what caused the conflists

2024-07-02 11:19 UTC, Mr-Sunglasses approved these changes
Thanks @SAMAD101

2024-07-02 11:19 UTC, merged